# Generated by Django 6.0.4 on 2026-04-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='Director',
        ),
    ]
